# -*- coding: utf-8 -*-
"""C2S3 - Plotting, Visualizations in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5TTCSwujcDiemMZN6QF4mPrWKGJVRm1

# Chapter 2 - Session 3
# Plotting, Visualizations in Python

## Objectives
#### learn how to use python library call Matplotlib which is dedicated to plotting and visualization in python and also how to see image in our current python working space 

## Content
#### 1) Installation and Importing Matplotlib Library
#### 2) Plotting with Pyplot
#### 3) Visualizing Images with Pyplot

<hr>

for visualization in python, we use library call Matplotlib. Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension of NumPy library.

Matplotlib library can be used to plots like
    - line plot
    - histogram
    - scatter plot
    - 3D plots
    - images
    - and many more

# 1) Installation and Importing Matplotlib Library

First we have to install Matplotlib to the Python using pip3 command as below
    
    pip3 install matplotlib

if you use Anaconda, Matplotlib library is already installed by default

matplotlib is large library, in for most cases we just one to use one part of the library call "pyplot", so we will just only import that part of library as "plt"
"""

'''importing matplotlib library and numpy library'''

import matplotlib.pyplot as plt
import numpy as np

"""# 2) Plotting with Pyplot"""

'''example plotting from matplotlib library'''

'''line plot'''
a = np.array([-3, -2, -1, 0, 1, 2, 3])
b = np.square(a)
plt.plot(a, b)
plt.show()

'''scatter plot'''
a = np.random.randn(100)
b = np.random.randn(100)
plt.scatter(a, b)
plt.show()

"""### Exercise 1

Plot 2x^2+5x+5 function from values from 0 to 10

### Exercise 2

Plot Sine and Cosine function from values from 0 to 10

### Exercise 3

Below are the sea level data in mm from 1990 to 2010

sea_level = [6.232283458, 6.334645663, 6.35826771, 6.291338576, 6.499999993, 6.618110229, 6.787401568, 7.066929127, 6.665354324, 7.011811016, 7.062992119, 7.287401567, 7.381889756, 7.759842512, 7.740157472, 7.74409448, 7.917322827, 7.996062984, 8.350393692, 8.586614164, 8.901574794]

plot scatter plot x axis the year and y axis sea level

# 3) Visualizing Images with Pyplot
"""

'''lets first read a image to matrix'''

# import gdal
from osgeo import gdal

img = gdal.Open('.//data//srtm_57_08_1.tif') 
band = img.GetRasterBand(1) 
mat_srtm = band.ReadAsArray(0, 0, img.RasterXSize, img.RasterYSize)

'''image plot'''

plt.imshow(mat_srtm)
plt.show()

'''since, we know that, our valid value (elevation) range is from 0 to 3411 from our last session'''
'''so lets clip our value to that range to get better visualization'''

plt.imshow(mat_srtm, vmin=0, vmax=3500)
plt.show()

'''and we can specify our color maps too'''

plt.imshow(mat_srtm, vmin=0, vmax=3500, cmap='Purples')
plt.show()

"""for more information about imshow, please have a look at documentation 

    https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html
    
for more information about color maps have a look at documentation

    https://matplotlib.org/examples/color/colormaps_reference.html

### Exercise 4

Plot "srtm_57_08_1.tif" showing only elevations between 0 to 2000 m

### Exercise 5

Plot "srtm_57_08_1.tif" with shades of red color ramp
"""



